version: '3.3'
services:
  master:
    build: ./jenkins-master
    ports:
      - "50000:50000"
    volumes:
      - jenkins-log:/var/log/jenkins
      - jenkins-data:/var/jenkins_home
    networks:
      - jenkins-net
    secrets:
      - jenkins-user
      - jenkins-pass
  nginx:
    build: ./jenkins-nginx
    ports:
      - "80:80"
    networks:
      - jenkins-net
  slave:
    build: ./jenkins-slave
  android:
    image: aabhassinha/android
  proxy:
    image: ehazlett/docker-proxy:latest
    command: -i
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      jenkins-net:
        aliases:
          - proxy1 
volumes:
  jenkins-data:
  jenkins-log:
networks:
  jenkins-net:
secrets:
  jenkins-user:
    external: true
  jenkins-pass:
    external: true
